### ISSUE TITLE
Prod docker-compose example does not work

### ISSUE THREAD

**Issue by Seruojka** [python-gino/gino-aiohttp#4]
## Expected Behavior

Run the example aiohttp application

## Actual Behavior

docker compose cannot start service  ''**migration**''

## Steps to Reproduce the Problem

  1.  Git clone repo
  2.  run docker-compose build from prod example
  3.  get error

```plaintext
ERROR: Service 'migration' failed to build: The command '/bin/sh -c python -m venv /env && . /env/bin/activate && poetry install' returned a non-zero code: 1
```

## Specifications

* MacOs version: 10.15.4
* Docker desktop version: 2.3.0.2
* other python libs -> from repo

**Comment by fantix** [comment]
Sorry for the late reply! This is expected because the same example code is also used in the unit test, and I had to make the following hack for the test to run with the latest master, you can simply use the commented line instead to make it work locally:

https://github.com/python-gino/gino-aiohttp/blob/ab38b22676fbd084b25c219126bf68e395f99e77/examples/prod_aiohttp_demo/pyproject.toml#L10
